### ISSUE TITLE
allow for using run command in transient with optional shell script

### ISSUE THREAD

**Issue by CDitzel** [Silex/docker.el#132]
Often times I use run_docker.sh script for firing up a container since the amount of flags I pass to the docker run command is large. Would it be possible to be queried for the location of such a script as an option?

**Comment by Silex** [comment]
That sounds unrelated to the package... can you describe a bit more what you are doing, maybe with an example?

**Comment by CDitzel** [comment]
delighted to. Right now the package offers to run a container with R from an existing image and then prompts the user for an optional command. Why not an option "run via script' which allows to point to the location of a script that contains a run command with many flags that would otherwise be to cumbersome to manually construct from the offered arguments within the package

**Comment by Silex** [comment]
I don't understand why you'd want to use `R` and have the arguments loaded from `run_docker.sh` instead of simply running `M-& run_docker.sh` (running an asynchronous command).

Now if the question is more generally how to save presets of transient, maybe you can write elisp manipulating `transient-history` to your advantage.

@tarsius: I know you can `C-x C-s` to permanently save a transient value, but do you have any trick to save a custom set of arguments? Something like:

``` emacs
(defun load-image-run-arguments-foo ()
  (interactive)
  (alist-set 'docker-image-run "--rm -i -t" transient-history)))
```

(of course `alist-set` does not exist)

**Comment by tarsius** [comment]
I don't understand, but maybe I don't have to to be of help.

You can cycle through previously used values much the same way as for minibuffer completion using `M-p` and `M-n`. Does that qualify as a trick here? ;D

**Comment by Silex** [comment]
> You can cycle through previously used values much the same way as for minibuffer completion using `M-p` and `M-n`. Does that qualify as a trick here? ;D

:exploding_head: 

Amazing. Didn't know that trick. Thanks!

@CDitzel: that'd be enough for your answer (not having to set up the transient each time). You can also look at `transient-history-next` and use it as inspiration.
