### ISSUE TITLE
Support for stopped containers

### ISSUE THREAD

**Issue by maaroen** [Silex/docker.el#136]
Hello @Silex,

Is it possible to add support for stopped containers? Like what you would usually get by using docker ps -a?

That would be great, I'm missing this at the moment.

**Comment by Silex** [comment]
Well this is supposed to be the default already :sweat_smile:

https://github.com/Silex/docker.el/blob/master/docker-container.el#L273

But I realised if you never visit that popup then it's not set. I need to think of the proper fix, in the meantime you can simply press `l` and enable `-a`. This should stay enabled.

**Comment by Silex** [comment]
@maaroen: ping

**Comment by maaroen** [comment]
Hello @Silex ,

Hey sorry I was busy and forgot to check out your answer. Yea with l I enabled -a and now I an see the stopped containers!

Thanks again for the fast answers!

**Comment by Silex** [comment]
Just keeping this open to remember me about having it enabled by default if you never visited the options.

**Comment by pataquets** [comment]
@Silex : Since I'm using Spacemacs, I don't get the transient and it's also happening to me.
However, I've tried invoking `docker-container-ls` command and doing `l`. It works, but from time to time, it gets reset.

I'm an Elisp beginner. I can give it a stab and send a PR with some help (I've looked at the code, but not sure where to add it). Also, I've looked up for an [updated link](https://github.com/Silex/docker.el/blob/08745207332d940130a2357eb5c5e00fd88bd6af/docker-container.el#L273) for the code you referenced above, in case you need it.

**Comment by Silex** [comment]
@pataquets: the latest version on master should fix the issue, please comment if it doesn't.

**Comment by pataquets** [comment]
Thanks, @Silex !
I'm getting `eval-buffer: Symbol’s function definition is void: docker-utils-define-transient-arguments` on all `docker-{containers,images,...} commands. If I find, select and evaluate the mentioned `defmacro` it works OK. however, be advised that I'm using Spacemacs and I can't rule out the culprit is there or in my config.
I'm just reporting, since I'll be AFK for some days, in case you can see something obvious.

**Comment by Silex** [comment]
Ah, I think I broke something by introducing a circular dependency 😅 

I have a fix almost ready, will keep you posted.

**Comment by Silex** [comment]
Should be fixed!

**Comment by pataquets** [comment]
Indeed, it is. Now it works. Thank you very much, @Silex
