### ISSUE TITLE
Add some CI to check byte compilation issues

### ISSUE THREAD

**Issue by Silex** [Silex/docker.el#191]
@LaurenceWarne 😉

**Comment by LaurenceWarne** [comment]
I was testing GH actions with [eldev](https://github.com/doublep/eldev/) on my fork, and I kept getting the really weird byte-comp error on CI:
```elisp
docker-compose.el:309:1:Warning: the function ‘transient-default-value’ is not
    known to be defined.
```
This was a bit :thinking: since it didn't show up with the previous byte-comp errors.  I thought there was some kind of error with `eldev compile`, it turns out that `transient-default-value` was added *after* the `0.3.7` transient release so `eldev` was right all along since it was installing that exact tag rather than from master :smile: :smile:  :smile: 

I have a branch warm anyway, I can PR after `transient` cuts a new release :slightly_smiling_face:

**Comment by Silex** [comment]
Well sorry I should have specified, I'd like to use https://github.com/purcell/nix-emacs-ci :sweat_smile: 

I opened this issue as a reminder, if you want to help go for it otherwise it's fine if you do nothing :wink:

**Comment by LaurenceWarne** [comment]
Yeah I'm currently using: https://github.com/purcell/setup-emacs, `eldev` on top of that is just for easy dep resolution and gives a nice way in CI to check byte-comp :slightly_smiling_face: :

https://github.com/LaurenceWarne/docker.el/blob/add-ci/.github/workflows/test.yml

**Comment by Silex** [comment]
Following in in the PR then :wink:
