### ISSUE TITLE
"Run" Doesn't Launch Vterm By Default

### ISSUE THREAD

**Issue by tompurl** [Silex/docker.el#207]
When issuing the 'run' command on an image using `docker.el` the shell is opened using `shell.el`, not `vterm`. I have `vterm` installed and can open shells with it.

I am using Spacemacs on Emacs 28.1 and the `docker` layer. I am also using the `shell` layer with the following config:

```
     (shell :variables
            shell-default-height 30
            shell-default-position 'bottom
            shell-default-shell 'vterm)
```

Here's my `docker.el` customizations:

```
  (with-eval-after-load 'docker
    (require 'vterm)
    (setq docker-command "podman")
    (add-to-list
     'docker-image-run-custom-args
     `(".\/foofile"
       ("-v $HOME/.kube:/root/.kube -v $HOME/git/foo/bar:/wd --workdir /wd --network=host" . ,docker-image-run-default-args)))
  )
```

Emacs runs within Ubuntu 20.04 on WSL2, Windows 10 and VcXsrv.

**Comment by LaurenceWarne** [comment]
I had a quick look and saw: https://github.com/Silex/docker.el/blob/670b7c346ba562614c27b68c04723af784978c15/docker-process.el#L43 so if `vterm` is loaded after `docker`, this var would always be set as `docker-run-async-with-buffer-shell` rather than `docker-run-async-with-buffer-vterm`.

 Does (A) `(require 'vterm)` before loading `docker` anywhere, or (B) `(setq docker-run-async-with-buffer-function #'docker-run-async-with-buffer-vterm)` do the trick?

**Comment by Silex** [comment]
Closing this as probably a configuration issue.
