### ISSUE TITLE
Make it all non-blocking

### ISSUE THREAD

**Issue by Silex** [Silex/docker.el#4]
Steal from magit-process :)

**Comment by Silex** [comment]
Ok, this is more or less solved by https://github.com/magit/magit/issues/1902

But maybe it's wise to wait the 1st of July when magit's next will be merged before depending on magit.

**Comment by jgkamat** [comment]
Is this still being worked on? I could provide some help for this (in ~4 weeks though...), as docker.el has been very helpful for me!

As far as I can tell you should be able to use `start-process-shell-command` instead of `shell-command-to-string` with little modifications (unless you were counting on the output or blocking in any way). It would also be nice to have notifications when a pull ends in the minibuffer if that would be possible.

**Comment by Silex** [comment]
Hello!

> Is this still being worked on? I could provide some help for this (in ~4 weeks though...), as docker.el has been very helpful for me!

Well yes it's in the pipeline... but I don't have much time to work on docker.el at the moment.

> As far as I can tell you should be able to use start-process-shell-command instead of shell-command-to-string with little modifications (unless you were counting on the output or blocking in any way). It would also be nice to have notifications when a pull ends in the minibuffer if that would be possible.

The problem is that we *do* use the output for many commands :-)
 
> Theres also async

Async works by spawning a 2nd emacs instance... it's not ideal. My plan is to reuse `magit-process`  (see https://github.com/magit/magit/issues/1902), but from my quick tests it didn't work as planned... I need to spend some time on it to try again.

**Comment by jgkamat** [comment]
Thanks for the update! I'll take a look around and see if I can help out sometime in the future if this is still being worked on.

**Comment by Silex** [comment]
It's DONE :tada:
