### ISSUE TITLE
Add command for viewing volume data.

### ISSUE THREAD

**Issue by Fuco1** [Silex/docker.el#85]
Something that would open a dired with the volume's content.

We can maybe hack it somehow by changing the insert directory function to something like:

    docker run --rm -v yarn_cache:/data busybox ls -alh /data

Maybe there are better options though.

**Comment by Silex** [comment]
Good idea.

it's as simple as `docker inspect -f "{{ .Mountpoint }}"  VOLUME`... I'll see what I can do in the next days.

**Comment by Silex** [comment]
Doesn't `ls -alh /var/lib/docker/volumes/yarn_cache/_data` show the same thing?

**Comment by Fuco1** [comment]
Ah, I see.

Yes that works but the files are owned by root so I would need `sudo` to run `ls`.

**Comment by Silex** [comment]
That works:

``` elisp
(defun dired-volume (name)
  (interactive "sVolume: ")
  (let ((path (docker-run "inspect" "-f" "\"{{ .Mountpoint }}\"" name)))
    (dired (format "/sudo::%s" path))))
```

But yeah, requires sudo. Your busybox trick has several problems:

- needs to pull the busybox image the first time.
- in order to use `dired`, you need TRAMP `/docker:container:PATH`, which is fine but that means you spawn the container, then enter dired... then when is this container erased? Even with `--rm` you need to know when to quit the container, maybe by overloading `q` in `dired`.

It actually makes more sense to provide this feature in the containers popup, and not the volumes popup. With the containers popup, you already have a container so you know which image to use... but then what if the container is not running? oh well, it's more complicated than it seems :sweat_smile:

**Comment by Fuco1** [comment]
The command would be run once and the container would be removed immediately after.  The output would be used as input for dired.  You don't need tramp for this.  You can run dired on pretty much any buffer that "kind of" looks like output of `ls`.

On the first run it would need to have a locally overwritten value of `insert-directory-program` and it would need to be marked as permanent (https://github.com/Fuco1/Fuco1.github.io/issues/7) to preserve it between reverts.

**Comment by Fuco1** [comment]
However I think the sudo solution is pretty damn good.  It's not really any slower and not a usability problem as the password can be cached.

**Comment by Silex** [comment]
> The command would be run once and the container would be removed immediately after. The output would be used as input for dired. You don't need tramp for this. You can run dired on pretty much any buffer that "kind of" looks like output of ls.

Hum, would rename/delete/etc on the files still work?

**Comment by Fuco1** [comment]
True, renames and so on would not work (well, you could make it work by hacking default directories and stuff but... meh).

**Comment by Silex** [comment]
Alright, https://github.com/Silex/docker.el/commit/e06f2e1e9e18926f959bd2aa937fe58d07bd01aa should do what you need :wink: 

Press `d` in `docker-volumes`.
