### ISSUE TITLE
`*docker-compose logs*` buffer should be read only

### ISSUE THREAD

**Issue by take-cheeze** [Silex/docker.el#98]

**Comment by Silex** [comment]
Right... at the moment it just uses `async-shell-command`, I'll see if there's something sensible to do.

**Comment by take-cheeze** [comment]
magit seems to use `dired-do-async-shell-command`
https://github.com/magit/magit/blob/ad130229cbde10af16276f0ef2882aa7a5f40170/lisp/magit-extras.el#L167-L176

**Comment by Silex** [comment]
Okay, `dired-do-async-shell-command` is for when you work on a file, so it makes sense to reuse it in magit's case, but not here.

For now I'm not sure this is worth fixing, especially since it might all change when I finally get to work on https://github.com/Silex/docker.el/issues/4

Just curious, do you have a problem with the buffer not being read-only except design-wise?

**Comment by take-cheeze** [comment]
As long as I care not to delete logs there is not much problem. I can wait #4 .

**Comment by Silex** [comment]
This should be ok now as it's `shell-mode` or `vterm-mode` that handles the buffer.
